/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.Ctrl_Cliente;
import controlador.Ctrl_Correo;
import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import modelo.Modelo_Cliente;

/**
 *
 * @author Edward
 */
public class InterCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterMotocicleta
     */
    private int obtenerIdCategoria = 0;
    public int codigo = (int) (Math.random() * 9000) + 1000;
    ;
    private boolean auxiliar = false;
    Modelo_Cliente cliente;

    public InterCliente() {

        initComponents();
        this.setSize(new Dimension(600, 420));
        this.setTitle("Nuevo Cliente");
        this.setClosable(false);
        this.setIconifiable(false);
        this.setBorder(null);

        this.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE); //no permite el movimiento del internal
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null); // desactiva la abrra de titulo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoVerificar = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        btnAceptarEnvio = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblCApellido = new javax.swing.JLabel();
        lblCNombre = new javax.swing.JLabel();
        lblCTelefono = new javax.swing.JLabel();
        lblCDireccion = new javax.swing.JLabel();
        lblCCorreo = new javax.swing.JLabel();
        lblCCedula = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ConfirmarCorreo = new javax.swing.JDialog();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtCodigoCorreo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        jPrefijos1 = new prefijovisual.JPrefijos();
        jLabel5 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        dialogoVerificar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("¿Desea confirmar los siguientes datos?");
        dialogoVerificar.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 260, 40));

        btnAceptarEnvio.setBackground(new java.awt.Color(204, 204, 204));
        btnAceptarEnvio.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btnAceptarEnvio.setText("Aceptar");
        btnAceptarEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarEnvioActionPerformed(evt);
            }
        });
        dialogoVerificar.getContentPane().add(btnAceptarEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        dialogoVerificar.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Apellido:");
        dialogoVerificar.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre:");
        dialogoVerificar.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Teléfono:");
        dialogoVerificar.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Direccion:");
        dialogoVerificar.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Correo:");
        dialogoVerificar.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("cedula:");
        dialogoVerificar.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lblCApellido.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lblCApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblCApellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dialogoVerificar.getContentPane().add(lblCApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 20));

        lblCNombre.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lblCNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblCNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dialogoVerificar.getContentPane().add(lblCNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 160, 20));

        lblCTelefono.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lblCTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblCTelefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dialogoVerificar.getContentPane().add(lblCTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 190, 20));

        lblCDireccion.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lblCDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblCDireccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dialogoVerificar.getContentPane().add(lblCDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 170, 20));

        lblCCorreo.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lblCCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dialogoVerificar.getContentPane().add(lblCCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 190, 20));

        lblCCedula.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lblCCedula.setForeground(new java.awt.Color(255, 255, 255));
        lblCCedula.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dialogoVerificar.getContentPane().add(lblCCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 160, 20));

        jLabel21.setBackground(new java.awt.Color(204, 204, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Azul.jpg"))); // NOI18N
        jLabel21.setOpaque(true);
        dialogoVerificar.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 200));

        ConfirmarCorreo.setAlwaysOnTop(true);
        ConfirmarCorreo.setModal(true);
        ConfirmarCorreo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        ConfirmarCorreo.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        ConfirmarCorreo.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ingrese el código que fue enviado a su correo:");
        ConfirmarCorreo.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        txtCodigoCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCodigoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCorreoActionPerformed(evt);
            }
        });
        ConfirmarCorreo.getContentPane().add(txtCodigoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 320, 30));

        jLabel23.setBackground(new java.awt.Color(204, 204, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Azul.jpg"))); // NOI18N
        jLabel23.setOpaque(true);
        ConfirmarCorreo.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 120));

        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(808, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 310, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cedula:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Direccion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, 20));

        txtNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 240, 30));

        txtApellido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 240, 30));

        txtCedula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 240, 30));

        txtDireccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 240, 30));

        txtCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 240, 30));

        btnAñadir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAñadir.setText("Aceptar");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 120, 40));

        jPrefijos1.setColorLada(java.awt.Color.white);
        getContentPane().add(jPrefijos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Azul.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        Modelo_Cliente cliente = new Modelo_Cliente();
        Ctrl_Cliente ctrl_Cliente = new Ctrl_Cliente();
        if (verificarDatos()) {
            if (ctrl_Cliente.existeCliente(txtCedula.getText())) {

                dialogoVerificar.setSize(560, 200);
                dialogoVerificar.setLocation(483, 199);
                dialogoVerificar.setVisible(true);
                lblCNombre.setText(txtNombre.getText());
                lblCApellido.setText(txtApellido.getText());
                lblCDireccion.setText(txtDireccion.getText());
                lblCTelefono.setText(jPrefijos1.getLada() + jPrefijos1.getNumero());
                lblCCorreo.setText(txtCorreo.getText());
                lblCCedula.setText(txtCedula.getText());
            } else {
                JOptionPane.showMessageDialog(null, "La cedula ya existe");
            }
        }
    }//GEN-LAST:event_btnAñadirActionPerformed

    private boolean verificarDatos() {
        if (txtNombre.getText().equals("") || txtApellido.getText().equals("") || txtDireccion.getText().equals("") || txtCorreo.getText().equals("") || txtCedula.getText().equals("")) {
           JOptionPane.showMessageDialog(null, " Rellene todos los campos");
            return false;
        } else {
            if (txtNombre.getText().matches("[a-zA-Z ]+") || txtApellido.getText().matches("[a-zA-Z ]+")) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Solo se aceptan letras en el nombre y apellido");
                return false;                
            }
        }
    }
    
    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed
    private String codig = "";
    private void btnAceptarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEnvioActionPerformed
        dialogoVerificar.dispose();
        if (!txtCorreo.getText().isEmpty()) {
            Ctrl_Cliente ctrl_Cliente = new Ctrl_Cliente();
            if (!ctrl_Cliente.existeCorreo(txtCorreo.getText())) {
                Ctrl_Correo ctrlCorreo = new Ctrl_Correo();
                codig = "" + ctrlCorreo.sendEmail(txtCorreo.getText().trim());
                ConfirmarCorreo.setLocation(100, 100);
                ConfirmarCorreo.setSize(400, 130);
                ConfirmarCorreo.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "El correo ya esta en uso");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingresa el correo para validarlo");
        }
        //enviarCorreo();
        this.limpiar();
    }//GEN-LAST:event_btnAceptarEnvioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        verificar();        // String b add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    private void verificar() {
        if (txtCodigoCorreo.getText().equals("" + codig)) {
            Modelo_Cliente cliente = new Modelo_Cliente();
            Ctrl_Cliente ctrl_Cliente = new Ctrl_Cliente();
            cliente.setNombre(txtNombre.getText().trim());
            cliente.setApellido(txtApellido.getText().trim());
            cliente.setCedula(txtCedula.getText().trim());
            cliente.setTelefono(jPrefijos1.getLada() + jPrefijos1.getNumero().trim());
            cliente.setDireccion(txtDireccion.getText().trim());
            cliente.setCorreo(txtCorreo.getText().trim());
            ctrl_Cliente.guardarCliente(cliente);
            ConfirmarCorreo.dispose();
            JOptionPane.showMessageDialog(null, "Cliente registrado exitosamente");
        } else {
            JOptionPane.showMessageDialog(null, "Codigo Incorrecto");
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dialogoVerificar.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ConfirmarCorreo.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtCodigoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCorreoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ConfirmarCorreo;
    private javax.swing.JButton btnAceptarEnvio;
    public static javax.swing.JButton btnAñadir;
    private javax.swing.JDialog dialogoVerificar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private prefijovisual.JPrefijos jPrefijos1;
    private javax.swing.JLabel lblCApellido;
    private javax.swing.JLabel lblCCedula;
    private javax.swing.JLabel lblCCorreo;
    private javax.swing.JLabel lblCDireccion;
    private javax.swing.JLabel lblCNombre;
    private javax.swing.JLabel lblCTelefono;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigoCorreo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    //Metodo para llenar el comboBox
    //Metodo para asignar idCategoria
    private void limpiar() {
        txtApellido.setText(null);
        txtCorreo.setText(null);
        txtCedula.setText(null);
        txtNombre.setText(null);
        txtDireccion.setText(null);
        jPrefijos1.setNumero(null);
    }

}
