/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

//Paquetes y librerias
import controlador.Ctrl_Usuario;
import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import modelo.Modelo_Usuario;

public class InterUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterMotocicleta
     */
    public InterUsuario() {
        initComponents();
        this.setSize(new Dimension(600, 450));
            this.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE); //no permite el movimiento del internal
           ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null); // desactiva la abrra de titulo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        btnMostrarC = new javax.swing.JButton();
        cbotipoU = new javax.swing.JComboBox<>();
        lblTipo = new javax.swing.JLabel();
        jPrefijos1 = new prefijovisual.JPrefijos();
        jLabel5 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(808, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 20, 290, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 240, 30));

        txtApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 240, 30));

        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 240, 30));

        btnAñadir.setBackground(new java.awt.Color(153, 153, 255));
        btnAñadir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 150, 40));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 240, 30));

        btnMostrarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ocultar.png"))); // NOI18N
        btnMostrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 30, 30));

        cbotipoU.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbotipoU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo de usuario:", "Cajero", "Gerente", "Administrador" }));
        getContentPane().add(cbotipoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 240, 30));

        lblTipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setText("Tipo Usuario:");
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        jPrefijos1.setColorLada(java.awt.Color.white);
        getContentPane().add(jPrefijos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Azul.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 817, 636));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed

        Modelo_Usuario usuario = new Modelo_Usuario();
        Ctrl_Usuario ctrl_Usuario = new Ctrl_Usuario();

        if (verificarDatos()) {
            if (!ctrl_Usuario.existeUsuario(txtUsuario.getText().trim())) {
                String combo = "" + cbotipoU.getSelectedItem();
                if (!combo.equalsIgnoreCase("Seleccione un tipo de usuario:")) 
                {
                    usuario.setNombre(txtNombre.getText().trim());
                    usuario.setApellido(txtApellido.getText().trim());
                    usuario.setUsuario(txtUsuario.getText().trim());
            usuario.setTelefono(jPrefijos1.getNumero().trim());
                    usuario.setPassword(txtPassword.getText().trim());
                    usuario.setTipoU(combo);
                    System.out.println("El tipo de usuario seleccionado es");
                    System.out.println(combo);

                    if (ctrl_Usuario.guardarUsuario(usuario)) {
                        JOptionPane.showMessageDialog(null, "Registro Guardado");
                        limpiar();
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Error al guardar");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Selecciona un tipo de usuario");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El usuario ya existe en la BD");

            }
        } 
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnMostrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCActionPerformed
        char i = txtPassword.getEchoChar();
        if (i == 0) {
            txtPassword.setEchoChar('*');
        } else {
            txtPassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_btnMostrarCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnMostrarC;
    private javax.swing.JComboBox<String> cbotipoU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private prefijovisual.JPrefijos jPrefijos1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    //Metodo para llenar el comboBox
    //Metodo para asignar idCategoria
    private void limpiar() {
        txtApellido.setText(null);
        txtUsuario.setText(null);
        txtNombre.setText(null);
        txtPassword.setText(null);
      jPrefijos1.setNumero(null);
        cbotipoU.setSelectedIndex(0);
    }
    
    private boolean verificarDatos() {
        if (txtNombre.getText().equals("") || txtApellido.getText().equals("") || txtUsuario.getText().equals("") || jPrefijos1.getNumero().equals("") || txtPassword.getText().equals("")) {
             JOptionPane.showMessageDialog(null, "Rellene todos los campos");
            return false;
        } else {
            if (txtNombre.getText().matches("[a-zA-Z ]+") || txtApellido.getText().matches("[a-zA-Z ]+")) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Solo se aceptan letras en el nombre y apellido");
                return false;                
            }
        }
    }
}
