package vista;

import controlador.Reportes;
import desplazable.Desface;
import java.awt.Color;
import java.awt.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import modelo.Modelo_Usuario;

/**
 *
 * @author jc389
 */
public class Sistema extends javax.swing.JFrame {

    private int idCliente;
    Desface desplazable;
    Reportes r = new Reportes();

    public Sistema() {
        initComponents();
        desplazable = new Desface();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        adaptarImagen();
        restriccionUser();
    }

    public void desplegar() {
        desplazable.desplazarDerecha(panelDesplazable, panelDesplazable.getX(), 0, 10, 5);
    }

    public void regresar() {
        desplazable.desplazarIzquierda(panelDesplazable, panelDesplazable.getX(), -380, 10, 1);
        btnMenu.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        suzukiPng = new javax.swing.JLabel();
        panelDesplazable = new javax.swing.JPanel();
        logoPanel = new javax.swing.JLabel();
        btnClientes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnMenuRegreso = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnCerrarSesión = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnGraficos = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        opcioonCliente = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        adMinistrarCliente = new javax.swing.JLabel();
        lblAgregarCliente = new javax.swing.JLabel();
        opcionUsuario = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        Gestionarusuario = new javax.swing.JLabel();
        nuevoUsuario = new javax.swing.JLabel();
        opcionProducto = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        verProducto = new javax.swing.JLabel();
        nuevoProducto = new javax.swing.JLabel();
        opcionVenta = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        realizarVenta = new javax.swing.JLabel();
        obtenerRegistro = new javax.swing.JLabel();
        Reporte = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        RVenta = new javax.swing.JLabel();
        opcionGrafico = new javax.swing.JPanel();
        RVenta1 = new javax.swing.JLabel();
        opcionReporte = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        reporteUsuarios = new javax.swing.JLabel();
        reporteClientes = new javax.swing.JLabel();
        reporteVentas = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        EtiquetaFondo2 = new javax.swing.JLabel();
        TablaPanel = new javax.swing.JTabbedPane();
        Defecto = new javax.swing.JPanel();
        gif = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AgregarCliente = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        interCliente1 = new vista.InterCliente();
        GestionarCliente = new javax.swing.JPanel();
        interGestionarCliente1 = new vista.InterGestionarCliente();
        Producto = new javax.swing.JPanel();
        interMotocicleta1 = new vista.InterMotocicleta();
        gestionarProducto = new javax.swing.JPanel();
        interGestionarMotos2 = new vista.InterGestionarMotos();
        AgregarUsuario = new javax.swing.JPanel();
        interUsuario2 = new vista.InterUsuario();
        gestionarUsuario = new javax.swing.JPanel();
        interGestionarUsuario1 = new vista.InterGestionarUsuario();
        Venta = new javax.swing.JPanel();
        interFacturacion1 = new vista.InterFacturacion();
        GestionarVenta = new javax.swing.JPanel();
        interGestionarVenta2 = new vista.InterGestionarVenta();
        GenerarGrafico = new javax.swing.JPanel();
        graficos1 = new vista.Graficos();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 1366));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setBackground(new java.awt.Color(204, 204, 204));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu3Lineas.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        suzukiPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/suzukiSistema.png"))); // NOI18N
        getContentPane().add(suzukiPng, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 171, 40));

        panelDesplazable.setBackground(new java.awt.Color(51, 51, 51));
        panelDesplazable.setPreferredSize(new java.awt.Dimension(220, 200));
        panelDesplazable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDesplazableMouseExited(evt);
            }
        });
        panelDesplazable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/suzukiSistema.png"))); // NOI18N
        panelDesplazable.add(logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 220, 40));

        btnClientes.setBackground(new java.awt.Color(51, 51, 51));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setAutoscrolls(true);
        btnClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnClientes.setBorderPainted(false);
        btnClientes.setContentAreaFilled(false);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnClientes.setOpaque(true);
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        panelDesplazable.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);
        panelDesplazable.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 320, 2));

        btnMenuRegreso.setBackground(new java.awt.Color(51, 51, 51));
        btnMenuRegreso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMenuRegreso.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuRegreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu3Lineas.png"))); // NOI18N
        btnMenuRegreso.setText("Menu");
        btnMenuRegreso.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnMenuRegreso.setBorderPainted(false);
        btnMenuRegreso.setContentAreaFilled(false);
        btnMenuRegreso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenuRegreso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuRegreso.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMenuRegreso.setOpaque(true);
        btnMenuRegreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuRegresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuRegresoMouseExited(evt);
            }
        });
        btnMenuRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRegresoActionPerformed(evt);
            }
        });
        panelDesplazable.add(btnMenuRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        btnUsuarios.setBackground(new java.awt.Color(51, 51, 51));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUsuarios.setOpaque(true);
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseExited(evt);
            }
        });
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        panelDesplazable.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 40));

        btnProducto.setBackground(new java.awt.Color(51, 51, 51));
        btnProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Moto.png"))); // NOI18N
        btnProducto.setText("Producto");
        btnProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnProducto.setBorderPainted(false);
        btnProducto.setContentAreaFilled(false);
        btnProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProducto.setOpaque(true);
        btnProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductoMouseExited(evt);
            }
        });
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });
        panelDesplazable.add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, 40));

        btnCerrarSesión.setBackground(new java.awt.Color(51, 51, 51));
        btnCerrarSesión.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCerrarSesión.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        btnCerrarSesión.setText("Cerrar Sesión");
        btnCerrarSesión.setToolTipText("");
        btnCerrarSesión.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnCerrarSesión.setBorderPainted(false);
        btnCerrarSesión.setContentAreaFilled(false);
        btnCerrarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrarSesión.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarSesión.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCerrarSesión.setOpaque(true);
        btnCerrarSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesiónMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesiónMouseExited(evt);
            }
        });
        btnCerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesiónActionPerformed(evt);
            }
        });
        panelDesplazable.add(btnCerrarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 160, 40));

        btnVentas.setBackground(new java.awt.Color(51, 51, 51));
        btnVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DINERO.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnVentas.setBorderPainted(false);
        btnVentas.setContentAreaFilled(false);
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVentas.setOpaque(true);
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVentasMouseExited(evt);
            }
        });
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        panelDesplazable.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 40));

        btnGraficos.setBackground(new java.awt.Color(51, 51, 51));
        btnGraficos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGraficos.setForeground(new java.awt.Color(255, 255, 255));
        btnGraficos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registroo.png"))); // NOI18N
        btnGraficos.setText("Gráficas");
        btnGraficos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnGraficos.setBorderPainted(false);
        btnGraficos.setContentAreaFilled(false);
        btnGraficos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGraficos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGraficos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGraficos.setOpaque(true);
        btnGraficos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGraficosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGraficosMouseExited(evt);
            }
        });
        btnGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficosActionPerformed(evt);
            }
        });
        panelDesplazable.add(btnGraficos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 160, 60));

        btnReportes.setBackground(new java.awt.Color(51, 51, 51));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registroo.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnReportes.setBorderPainted(false);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReportes.setOpaque(true);
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportesMouseExited(evt);
            }
        });
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        panelDesplazable.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 160, 60));

        opcioonCliente.setBackground(new java.awt.Color(51, 51, 51));
        opcioonCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator2.setOpaque(true);
        opcioonCliente.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 164, 1));

        adMinistrarCliente.setBackground(new java.awt.Color(51, 51, 51));
        adMinistrarCliente.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        adMinistrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        adMinistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GestionarCleinte.png"))); // NOI18N
        adMinistrarCliente.setText("Consultar Clientes");
        adMinistrarCliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        adMinistrarCliente.setOpaque(true);
        adMinistrarCliente.setPreferredSize(new java.awt.Dimension(20, 20));
        adMinistrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adMinistrarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adMinistrarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adMinistrarClienteMouseExited(evt);
            }
        });
        opcioonCliente.add(adMinistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 21, 160, 19));

        lblAgregarCliente.setBackground(new java.awt.Color(51, 51, 51));
        lblAgregarCliente.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lblAgregarCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarCliente.png"))); // NOI18N
        lblAgregarCliente.setText("Agregar Cliente");
        lblAgregarCliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblAgregarCliente.setOpaque(true);
        lblAgregarCliente.setPreferredSize(new java.awt.Dimension(20, 20));
        lblAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAgregarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAgregarClienteMouseExited(evt);
            }
        });
        opcioonCliente.add(lblAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 19));

        panelDesplazable.add(opcioonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 40));

        opcionUsuario.setBackground(new java.awt.Color(51, 51, 51));
        opcionUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator3.setOpaque(true);
        opcionUsuario.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, -1, 2));

        Gestionarusuario.setBackground(new java.awt.Color(51, 51, 51));
        Gestionarusuario.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        Gestionarusuario.setForeground(new java.awt.Color(255, 255, 255));
        Gestionarusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GestionarUser.png"))); // NOI18N
        Gestionarusuario.setText("Gestionar Usuario");
        Gestionarusuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        Gestionarusuario.setOpaque(true);
        Gestionarusuario.setPreferredSize(new java.awt.Dimension(20, 20));
        Gestionarusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GestionarusuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GestionarusuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GestionarusuarioMouseExited(evt);
            }
        });
        opcionUsuario.add(Gestionarusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 21, 160, 19));

        nuevoUsuario.setBackground(new java.awt.Color(51, 51, 51));
        nuevoUsuario.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        nuevoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        nuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarUser.png"))); // NOI18N
        nuevoUsuario.setText("Nuevo Usuario");
        nuevoUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        nuevoUsuario.setOpaque(true);
        nuevoUsuario.setPreferredSize(new java.awt.Dimension(20, 20));
        nuevoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevoUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevoUsuarioMouseExited(evt);
            }
        });
        opcionUsuario.add(nuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 19));

        panelDesplazable.add(opcionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 156, 40));

        opcionProducto.setBackground(new java.awt.Color(51, 51, 51));
        opcionProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator4.setOpaque(true);
        opcionProducto.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 159, 1));

        verProducto.setBackground(new java.awt.Color(51, 51, 51));
        verProducto.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        verProducto.setForeground(new java.awt.Color(255, 255, 255));
        verProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verProductos.png"))); // NOI18N
        verProducto.setText("Ver mis Productos");
        verProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        verProducto.setOpaque(true);
        verProducto.setPreferredSize(new java.awt.Dimension(20, 20));
        verProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProductoMouseExited(evt);
            }
        });
        opcionProducto.add(verProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 21, 160, 19));

        nuevoProducto.setBackground(new java.awt.Color(51, 51, 51));
        nuevoProducto.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        nuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        nuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarProducto.png"))); // NOI18N
        nuevoProducto.setText("Nuevo Producto");
        nuevoProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        nuevoProducto.setOpaque(true);
        nuevoProducto.setPreferredSize(new java.awt.Dimension(20, 20));
        nuevoProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevoProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevoProductoMouseExited(evt);
            }
        });
        opcionProducto.add(nuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 19));

        panelDesplazable.add(opcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 159, 40));

        opcionVenta.setBackground(new java.awt.Color(51, 51, 51));
        opcionVenta.setForeground(new java.awt.Color(255, 255, 255));
        opcionVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator5.setOpaque(true);
        opcionVenta.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 154, 1));

        realizarVenta.setBackground(new java.awt.Color(51, 51, 51));
        realizarVenta.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        realizarVenta.setForeground(new java.awt.Color(255, 255, 255));
        realizarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/realizarventa.png"))); // NOI18N
        realizarVenta.setText("Realizar Venta");
        realizarVenta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        realizarVenta.setOpaque(true);
        realizarVenta.setPreferredSize(new java.awt.Dimension(20, 20));
        realizarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                realizarVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                realizarVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                realizarVentaMouseExited(evt);
            }
        });
        opcionVenta.add(realizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 19));

        obtenerRegistro.setBackground(new java.awt.Color(51, 51, 51));
        obtenerRegistro.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        obtenerRegistro.setForeground(new java.awt.Color(255, 255, 255));
        obtenerRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registroventa.png"))); // NOI18N
        obtenerRegistro.setText("Obtener Registro");
        obtenerRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        obtenerRegistro.setOpaque(true);
        obtenerRegistro.setPreferredSize(new java.awt.Dimension(20, 20));
        obtenerRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obtenerRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                obtenerRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                obtenerRegistroMouseExited(evt);
            }
        });
        opcionVenta.add(obtenerRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 150, 19));

        panelDesplazable.add(opcionVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 156, 40));

        Reporte.setBackground(new java.awt.Color(51, 51, 51));
        Reporte.setForeground(new java.awt.Color(255, 255, 255));
        Reporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator6.setOpaque(true);
        Reporte.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 220, 1));

        RVenta.setBackground(new java.awt.Color(51, 51, 51));
        RVenta.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        RVenta.setForeground(new java.awt.Color(255, 255, 255));
        RVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registros.png"))); // NOI18N
        RVenta.setText("Generar Reporte de ventas");
        RVenta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        RVenta.setOpaque(true);
        RVenta.setPreferredSize(new java.awt.Dimension(20, 20));
        RVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RVentaMouseExited(evt);
            }
        });
        Reporte.add(RVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 19));

        panelDesplazable.add(Reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 200, 220, 20));

        opcionGrafico.setBackground(new java.awt.Color(51, 51, 51));
        opcionGrafico.setForeground(new java.awt.Color(255, 255, 255));
        opcionGrafico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RVenta1.setBackground(new java.awt.Color(51, 51, 51));
        RVenta1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        RVenta1.setForeground(new java.awt.Color(255, 255, 255));
        RVenta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registros.png"))); // NOI18N
        RVenta1.setText("Gráfico de Líneas");
        RVenta1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        RVenta1.setOpaque(true);
        RVenta1.setPreferredSize(new java.awt.Dimension(20, 20));
        RVenta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RVenta1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RVenta1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RVenta1MouseExited(evt);
            }
        });
        opcionGrafico.add(RVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 220, 19));

        panelDesplazable.add(opcionGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, 40));

        opcionReporte.setBackground(new java.awt.Color(51, 51, 51));
        opcionReporte.setForeground(new java.awt.Color(255, 255, 255));
        opcionReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator8.setOpaque(true);
        opcionReporte.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 160, 1));

        reporteUsuarios.setBackground(new java.awt.Color(51, 51, 51));
        reporteUsuarios.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        reporteUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        reporteUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registros.png"))); // NOI18N
        reporteUsuarios.setText("Reporte Productos");
        reporteUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        reporteUsuarios.setOpaque(true);
        reporteUsuarios.setPreferredSize(new java.awt.Dimension(20, 20));
        reporteUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reporteUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reporteUsuariosMouseExited(evt);
            }
        });
        opcionReporte.add(reporteUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 220, 19));

        reporteClientes.setBackground(new java.awt.Color(51, 51, 51));
        reporteClientes.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        reporteClientes.setForeground(new java.awt.Color(255, 255, 255));
        reporteClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registros.png"))); // NOI18N
        reporteClientes.setText("Reporte Clientes");
        reporteClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        reporteClientes.setOpaque(true);
        reporteClientes.setPreferredSize(new java.awt.Dimension(20, 20));
        reporteClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reporteClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reporteClientesMouseExited(evt);
            }
        });
        opcionReporte.add(reporteClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 19));

        reporteVentas.setBackground(new java.awt.Color(51, 51, 51));
        reporteVentas.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        reporteVentas.setForeground(new java.awt.Color(255, 255, 255));
        reporteVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registros.png"))); // NOI18N
        reporteVentas.setText("Reporte Ventas");
        reporteVentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        reporteVentas.setOpaque(true);
        reporteVentas.setPreferredSize(new java.awt.Dimension(20, 20));
        reporteVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reporteVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reporteVentasMouseExited(evt);
            }
        });
        opcionReporte.add(reporteVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 19));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator9.setOpaque(true);
        opcionReporte.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 160, 1));

        panelDesplazable.add(opcionReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 160, 60));

        getContentPane().add(panelDesplazable, new org.netbeans.lib.awtextra.AbsoluteConstraints(-380, 0, 380, 768));

        EtiquetaFondo2.setBackground(new java.awt.Color(204, 204, 204));
        EtiquetaFondo2.setOpaque(true);
        getContentPane().add(EtiquetaFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 40));

        TablaPanel.setOpaque(true);

        Defecto.setBackground(new java.awt.Color(255, 255, 255));
        Defecto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gif3.gif"))); // NOI18N
        Defecto.add(gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 600, 450));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO");
        Defecto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 250, 70));

        TablaPanel.addTab("Inicio", Defecto);

        AgregarCliente.setBackground(new java.awt.Color(29, 29, 47));
        AgregarCliente.setMinimumSize(new java.awt.Dimension(200, 200));
        AgregarCliente.setPreferredSize(new java.awt.Dimension(200, 200));
        AgregarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("CANCELAR");
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        AgregarCliente.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 610, 120, 40));

        interCliente1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        interCliente1.setVisible(true);
        AgregarCliente.add(interCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 47, -1, -1));

        TablaPanel.addTab("NuevoCliente", AgregarCliente);

        GestionarCliente.setBackground(new java.awt.Color(153, 153, 153));
        GestionarCliente.setMinimumSize(new java.awt.Dimension(200, 200));
        GestionarCliente.setPreferredSize(new java.awt.Dimension(200, 200));
        GestionarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        interGestionarCliente1.setVisible(true);
        GestionarCliente.add(interGestionarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        TablaPanel.addTab("AdministrarCiente", GestionarCliente);

        Producto.setBackground(new java.awt.Color(40, 40, 60));
        Producto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        interMotocicleta1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        interMotocicleta1.setVisible(true);
        Producto.add(interMotocicleta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 47, -1, -1));

        TablaPanel.addTab("Producto", Producto);

        gestionarProducto.setBackground(new java.awt.Color(153, 153, 153));
        gestionarProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        interGestionarMotos2.setVisible(true);
        gestionarProducto.add(interGestionarMotos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        TablaPanel.addTab("Administrar", gestionarProducto);

        AgregarUsuario.setBackground(new java.awt.Color(29, 29, 47));
        AgregarUsuario.setMinimumSize(new java.awt.Dimension(200, 200));
        AgregarUsuario.setPreferredSize(new java.awt.Dimension(200, 200));
        AgregarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        interUsuario2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        interUsuario2.setVisible(true);
        AgregarUsuario.add(interUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 47, 817, 636));

        TablaPanel.addTab("Usuario", AgregarUsuario);

        gestionarUsuario.setBackground(new java.awt.Color(153, 153, 153));
        gestionarUsuario.setMinimumSize(new java.awt.Dimension(200, 200));
        gestionarUsuario.setPreferredSize(new java.awt.Dimension(200, 200));
        gestionarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        interGestionarUsuario1.setVisible(true);
        gestionarUsuario.add(interGestionarUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1366, 766));

        TablaPanel.addTab("Administrar", gestionarUsuario);

        Venta.setBackground(new java.awt.Color(153, 153, 153));
        Venta.setMinimumSize(new java.awt.Dimension(200, 200));
        Venta.setPreferredSize(new java.awt.Dimension(200, 200));
        Venta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        interFacturacion1.setVisible(true);
        Venta.add(interFacturacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        TablaPanel.addTab("Venta", Venta);

        GestionarVenta.setBackground(new java.awt.Color(153, 153, 153));
        GestionarVenta.setMinimumSize(new java.awt.Dimension(200, 200));
        GestionarVenta.setPreferredSize(new java.awt.Dimension(200, 200));
        GestionarVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        interGestionarVenta2.setVisible(true);
        GestionarVenta.add(interGestionarVenta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        TablaPanel.addTab("Gestionar", GestionarVenta);

        GenerarGrafico.setBackground(new java.awt.Color(153, 153, 153));
        GenerarGrafico.setMinimumSize(new java.awt.Dimension(200, 200));
        GenerarGrafico.setPreferredSize(new java.awt.Dimension(200, 200));
        GenerarGrafico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        graficos1.setVisible(true);
        GenerarGrafico.add(graficos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1366, 766));

        TablaPanel.addTab("Gestionar", GenerarGrafico);

        getContentPane().add(TablaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        desplegar();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void panelDesplazableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDesplazableMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelDesplazableMouseExited

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        opcionGrafico.setLocation(0, 220);
        desplazable.desplazarDerecha(opcioonCliente, opcioonCliente.getX(), 160, 10, -20);
        opcionVenta.setLocation(0, 160);
        opcionProducto.setLocation(0, 120);
        opcionUsuario.setLocation(0, 80);
        Reporte.setLocation(-60, 200);
        opcionReporte.setLocation(0, 260);

    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnMenuRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRegresoActionPerformed
        regresar();// TODO add your handling code here:
    }//GEN-LAST:event_btnMenuRegresoActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        desplazable.desplazarDerecha(opcionUsuario, opcionUsuario.getX(), 160, 10, -20);
        opcionVenta.setLocation(0, 160);
        opcionProducto.setLocation(0, 120);
        opcioonCliente.setLocation(0, 40);
        opcionReporte.setLocation(0, 260);
        Reporte.setLocation(-60, 200);// TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        btnClientes.setBackground(new Color(33, 30, 30));
        btnClientes.setForeground(new Color(46, 200, 197));
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        btnClientes.setBackground(new Color(51, 51, 51));
        btnClientes.setForeground(new Color(255, 255, 255));

    }//GEN-LAST:event_btnClientesMouseExited

    private void lblAgregarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarClienteMouseEntered
        lblAgregarCliente.setBackground(new Color(33, 30, 30));
        lblAgregarCliente.setForeground(new Color(46, 200, 197));
// TODO add your handling code here:
    }//GEN-LAST:event_lblAgregarClienteMouseEntered

    private void lblAgregarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarClienteMouseExited
        lblAgregarCliente.setBackground(new Color(51, 51, 51));
        lblAgregarCliente.setForeground(new Color(255, 255, 255));// TODO add your handling code here:
    }//GEN-LAST:event_lblAgregarClienteMouseExited

    private void adMinistrarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adMinistrarClienteMouseEntered
        adMinistrarCliente.setBackground(new Color(33, 30, 30));
        adMinistrarCliente.setForeground(new Color(46, 200, 197));// TODO add your handling code here:
    }//GEN-LAST:event_adMinistrarClienteMouseEntered

    private void adMinistrarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adMinistrarClienteMouseExited
        adMinistrarCliente.setBackground(new Color(51, 51, 51));
        adMinistrarCliente.setForeground(new Color(255, 255, 255));// TODO add your handling code here:
    }//GEN-LAST:event_adMinistrarClienteMouseExited

    private void GestionarusuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionarusuarioMouseEntered
        Gestionarusuario.setBackground(new Color(33, 30, 30));
        Gestionarusuario.setForeground(new Color(46, 200, 197));
    }//GEN-LAST:event_GestionarusuarioMouseEntered

    private void GestionarusuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionarusuarioMouseExited
        Gestionarusuario.setBackground(new Color(51, 51, 51));
        Gestionarusuario.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_GestionarusuarioMouseExited

    private void nuevoUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoUsuarioMouseEntered
        nuevoUsuario.setBackground(new Color(33, 30, 30));
        nuevoUsuario.setForeground(new Color(46, 200, 197));
    }//GEN-LAST:event_nuevoUsuarioMouseEntered

    private void nuevoUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoUsuarioMouseExited
        nuevoUsuario.setBackground(new Color(51, 51, 51));
        nuevoUsuario.setForeground(new Color(255, 255, 255));// TODO add your handling code here:
    }//GEN-LAST:event_nuevoUsuarioMouseExited

    private void verProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProductoMouseEntered
        verProducto.setBackground(new Color(33, 30, 30));
        verProducto.setForeground(new Color(46, 200, 197));
    }//GEN-LAST:event_verProductoMouseEntered

    private void verProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProductoMouseExited
        verProducto.setBackground(new Color(51, 51, 51));      // TODO add your handling code here:
        verProducto.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_verProductoMouseExited

    private void nuevoProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoProductoMouseEntered
        nuevoProducto.setBackground(new Color(33, 30, 30));
        nuevoProducto.setForeground(new Color(46, 200, 197));
    }//GEN-LAST:event_nuevoProductoMouseEntered

    private void nuevoProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoProductoMouseExited
        nuevoProducto.setBackground(new Color(51, 51, 51));
        nuevoProducto.setForeground(new Color(255, 255, 255));
// TODO add your handling code here:
    }//GEN-LAST:event_nuevoProductoMouseExited

    private void realizarVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarVentaMouseEntered
        realizarVenta.setBackground(new Color(33, 30, 30));
        realizarVenta.setForeground(new Color(46, 200, 197));
    }//GEN-LAST:event_realizarVentaMouseEntered

    private void realizarVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarVentaMouseExited
        realizarVenta.setBackground(new Color(51, 51, 51));
        realizarVenta.setForeground(new Color(255, 255, 255));
// TODO add your handling code here:
    }//GEN-LAST:event_realizarVentaMouseExited

    private void obtenerRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_obtenerRegistroMouseEntered
        obtenerRegistro.setBackground(new Color(33, 30, 30));
        obtenerRegistro.setForeground(new Color(46, 200, 197));
    }//GEN-LAST:event_obtenerRegistroMouseEntered

    private void obtenerRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_obtenerRegistroMouseExited
        obtenerRegistro.setBackground(new Color(51, 51, 51));
        obtenerRegistro.setForeground(new Color(255, 255, 255));// TODO add your handling code here:
    }//GEN-LAST:event_obtenerRegistroMouseExited

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        desplazable.desplazarDerecha(opcionVenta, opcionVenta.getX(), 160, 10, -20);
        opcioonCliente.setLocation(0, 40);
        opcionProducto.setLocation(0, 120);
        opcionGrafico.setLocation(0, 220);
        Reporte.setLocation(-60, 200);
        opcionReporte.setLocation(0, 260);
        opcionUsuario.setLocation(0, 80);// TODO add your handling code here:
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseEntered
        btnUsuarios.setBackground(new Color(33, 30, 30));
        btnUsuarios.setForeground(new Color(46, 200, 197));    // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosMouseEntered

    private void btnProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseEntered
        btnProducto.setBackground(new Color(33, 30, 30));
        btnProducto.setForeground(new Color(46, 200, 197));     // TODO add your handling code here:
    }//GEN-LAST:event_btnProductoMouseEntered

    private void btnVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseEntered
        btnVentas.setBackground(new Color(33, 30, 30));
        btnVentas.setForeground(new Color(46, 200, 197));       // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasMouseEntered

    private void btnUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseExited
        btnUsuarios.setBackground(new Color(51, 51, 51));
        btnUsuarios.setForeground(new Color(255, 255, 255));        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosMouseExited

    private void btnProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseExited
        btnProducto.setBackground(new Color(51, 51, 51));
        btnProducto.setForeground(new Color(255, 255, 255));// TODO add your handling code here:
    }//GEN-LAST:event_btnProductoMouseExited

    private void btnVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseExited
        btnVentas.setBackground(new Color(51, 51, 51));
        btnVentas.setForeground(new Color(255, 255, 255));// TODO add your handling code here:
    }//GEN-LAST:event_btnVentasMouseExited

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        desplazable.desplazarDerecha(opcionProducto, opcionProducto.getX(), 160, 10, -20);
        opcionGrafico.setLocation(0, 220);
        opcionVenta.setLocation(0, 160);
        opcioonCliente.setLocation(0, 40);
        Reporte.setLocation(-60, 200);
        opcionReporte.setLocation(0, 260);
        opcionUsuario.setLocation(0, 80);// TODO add your handling code here:
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnMenuRegresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuRegresoMouseExited
        btnMenuRegreso.setBackground(new Color(51, 51, 51));        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuRegresoMouseExited

    private void btnCerrarSesiónMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesiónMouseExited
        btnCerrarSesión.setBackground(new Color(51, 51, 51));
        btnCerrarSesión.setForeground(new Color(255, 255, 255));// TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesiónMouseExited

    private void btnCerrarSesiónMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesiónMouseEntered
        btnCerrarSesión.setBackground(new Color(153, 255, 153));        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesiónMouseEntered

    private void lblAgregarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarClienteMouseClicked
        TablaPanel.setSelectedIndex(1);
        btnMenu.setVisible(true);
        regresar();


    }//GEN-LAST:event_lblAgregarClienteMouseClicked
    private void cargarTablaClientes() {
        Connection cx = conexion.ConectionDB.conectar();
        DefaultTableModel dfT = new DefaultTableModel();
        String sql = "select *from cliente";
        Statement st;
        try {
            st = cx.createStatement();
            ResultSet rs = st.executeQuery(sql);

            dfT.addColumn("ID_CLIENTE");
            dfT.addColumn("Nombre");
            dfT.addColumn("Apellido");
            dfT.addColumn("Cedula");
            dfT.addColumn("Telefono");
            dfT.addColumn("Direccion");
            dfT.addColumn("Correo");
            dfT.addColumn("Estado");

            while (rs.next()) {

                Object fila[] = new Object[8];

                for (int i = 0; i < 8; i++) {
                    fila[i] = rs.getObject(i + 1);

                }
                dfT.addRow(fila);
            }
            cx.close();

        } catch (SQLException e) {
            System.out.println("Error al llenar la tabla clientes: " + e);
        }
    }
    private void adMinistrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adMinistrarClienteMouseClicked
        TablaPanel.setSelectedIndex(2);
        interGestionarCliente1.cargarTablaClientes();
        btnMenu.setVisible(true);
        regresar();// TODO add your handling code here:
    }//GEN-LAST:event_adMinistrarClienteMouseClicked

    private void nuevoProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoProductoMouseClicked
        TablaPanel.setSelectedIndex(3);
        btnMenu.setVisible(true);
        regresar();
// TODO add your handling code here:
    }//GEN-LAST:event_nuevoProductoMouseClicked

    private void verProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProductoMouseClicked
        interGestionarMotos2.cargarTablaMotos();
        TablaPanel.setSelectedIndex(4);

        btnMenu.setVisible(true);
        regresar();
    }//GEN-LAST:event_verProductoMouseClicked
    private void cargarGestion() {

    }
    private void btnMenuRegresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuRegresoMouseEntered

    }//GEN-LAST:event_btnMenuRegresoMouseEntered

    private void nuevoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoUsuarioMouseClicked
        TablaPanel.setSelectedIndex(5);
        btnMenu.setVisible(true);
        regresar();// TODO add your handling code here:
    }//GEN-LAST:event_nuevoUsuarioMouseClicked

    private void GestionarusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionarusuarioMouseClicked
        TablaPanel.setSelectedIndex(6);
        interGestionarUsuario1.cargarTablaUsuarios();
        btnMenu.setVisible(true);
        regresar();// TODO add your handling code here:
    }//GEN-LAST:event_GestionarusuarioMouseClicked

    private void realizarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarVentaMouseClicked
        interFacturacion1.cargarCBOMotos();
        interFacturacion1.cargarCBOClientes();
        TablaPanel.setSelectedIndex(7);
        btnMenu.setVisible(true);
        regresar();// TODO add your handling code here:
    }//GEN-LAST:event_realizarVentaMouseClicked

    private void obtenerRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_obtenerRegistroMouseClicked
        TablaPanel.setSelectedIndex(8);
        interGestionarVenta2.cargarTablaVentas();
        btnMenu.setVisible(true);
        regresar();// TODO add your handling code here:
    }//GEN-LAST:event_obtenerRegistroMouseClicked

    private void btnGraficosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficosMouseEntered
        // TODO add your handling code here:

        btnGraficos.setBackground(new Color(33, 30, 30));
        btnGraficos.setForeground(new Color(46, 200, 197));
    }//GEN-LAST:event_btnGraficosMouseEntered

    private void btnGraficosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficosMouseExited
        btnGraficos.setBackground(new Color(51, 51, 51));
        btnGraficos.setForeground(new Color(255, 255, 255));

    }//GEN-LAST:event_btnGraficosMouseExited
    private void adaptarImagen() {
        ImageIcon imagen = new ImageIcon("src/Imagenes/gifMoto.gif");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(gif.getWidth(), gif.getHeight(), Image.SCALE_DEFAULT));
        gif.setIcon(icono);
    }
    private void btnGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficosActionPerformed

        desplazable.desplazarDerecha(Reporte, Reporte.getX(), 160, 10, -20);
        opcioonCliente.setLocation(0, 40);
        opcionUsuario.setLocation(0, 80);
        opcionProducto.setLocation(0, 120);
        opcionReporte.setLocation(0, 260);
        opcionVenta.setLocation(0, 160);
// TODO add your handling code here:
    }//GEN-LAST:event_btnGraficosActionPerformed

    private void RVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RVentaMouseClicked
        desplazable.desplazarDerecha(opcionGrafico, opcionGrafico.getX(), 160, 10, -20);
    }//GEN-LAST:event_RVentaMouseClicked

    private void RVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RVentaMouseEntered
        RVenta.setBackground(new Color(33, 30, 30));
        RVenta.setForeground(new Color(46, 200, 197)); // TODO add your handling code here:
    }//GEN-LAST:event_RVentaMouseEntered

    private void RVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RVentaMouseExited
        RVenta.setBackground(new Color(51, 51, 51));
        RVenta.setForeground(new Color(255, 255, 255)); // TODO add your handling code here:
    }//GEN-LAST:event_RVentaMouseExited

    private void RVenta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RVenta1MouseClicked
        //graficos1.showLineChart();
        btnMenu.setVisible(true);
graficos1.limpiar();
        TablaPanel.setSelectedIndex(9);// TODO add your handling code here:
    }//GEN-LAST:event_RVenta1MouseClicked

    private void RVenta1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RVenta1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RVenta1MouseEntered

    private void RVenta1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RVenta1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RVenta1MouseExited

    private void btnReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesMouseEntered

    private void btnReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesMouseExited

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        desplazable.desplazarDerecha(opcionReporte, opcionReporte.getX(), 160, 10, 5);
        opcioonCliente.setLocation(0, 40);
        opcionUsuario.setLocation(0, 80);
        opcionProducto.setLocation(0, 120);
        opcionVenta.setLocation(0, 160);
        Reporte.setLocation(-60, 200);
// TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void reporteUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteUsuariosMouseClicked
        r.reportesMotocicletas();        // TODO add your handling code here:
    }//GEN-LAST:event_reporteUsuariosMouseClicked

    private void reporteUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteUsuariosMouseEntered
        reporteUsuarios.setBackground(new Color(33, 30, 30));
        reporteUsuarios.setForeground(new Color(46, 200, 197));  // TODO add your handling code here:
    }//GEN-LAST:event_reporteUsuariosMouseEntered

    private void reporteUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteUsuariosMouseExited
        reporteUsuarios.setBackground(new Color(51, 51, 51));
        reporteUsuarios.setForeground(new Color(255, 255, 255));   // TODO add your handling code here:
    }//GEN-LAST:event_reporteUsuariosMouseExited

    private void reporteClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteClientesMouseClicked

        r.reportesClientes();
    }//GEN-LAST:event_reporteClientesMouseClicked

    private void reporteClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteClientesMouseEntered
        reporteClientes.setBackground(new Color(33, 30, 30));
        reporteClientes.setForeground(new Color(46, 200, 197));// TODO add your handling code here:
    }//GEN-LAST:event_reporteClientesMouseEntered

    private void reporteClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteClientesMouseExited
        reporteClientes.setBackground(new Color(51, 51, 51));
        reporteClientes.setForeground(new Color(255, 255, 255));   // TODO add your handling code here:
    }//GEN-LAST:event_reporteClientesMouseExited

    private void reporteVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteVentasMouseClicked
        r.reportesVentas();        // TODO add your handling code here:
    }//GEN-LAST:event_reporteVentasMouseClicked

    private void reporteVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteVentasMouseEntered
        reporteVentas.setBackground(new Color(33, 30, 30));
        reporteVentas.setForeground(new Color(46, 200, 197)); // TODO add your handling code here:
    }//GEN-LAST:event_reporteVentasMouseEntered

    private void reporteVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteVentasMouseExited
        reporteVentas.setBackground(new Color(51, 51, 51));
        reporteVentas.setForeground(new Color(255, 255, 255));    // TODO add your handling code here:
    }//GEN-LAST:event_reporteVentasMouseExited

    private void btnCerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesiónActionPerformed
        FormLoggin loggin = new FormLoggin();
        loggin.setSize(new Dimension(700, 500));
        loggin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesiónActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TablaPanel.setSelectedIndex(0);
        btnMenu.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarCliente;
    private javax.swing.JPanel AgregarUsuario;
    private javax.swing.JPanel Defecto;
    private javax.swing.JLabel EtiquetaFondo2;
    private javax.swing.JPanel GenerarGrafico;
    private javax.swing.JPanel GestionarCliente;
    private javax.swing.JPanel GestionarVenta;
    private javax.swing.JLabel Gestionarusuario;
    private javax.swing.JPanel Producto;
    private javax.swing.JLabel RVenta;
    private javax.swing.JLabel RVenta1;
    private javax.swing.JPanel Reporte;
    public static javax.swing.JTabbedPane TablaPanel;
    private javax.swing.JPanel Venta;
    private javax.swing.JLabel adMinistrarCliente;
    private javax.swing.JButton btnCerrarSesión;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnGraficos;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMenuRegreso;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVentas;
    private javax.swing.JPanel gestionarProducto;
    private javax.swing.JPanel gestionarUsuario;
    private javax.swing.JLabel gif;
    private vista.Graficos graficos1;
    private vista.InterCliente interCliente1;
    private vista.InterFacturacion interFacturacion1;
    private vista.InterGestionarCliente interGestionarCliente1;
    private vista.InterGestionarMotos interGestionarMotos2;
    private vista.InterGestionarUsuario interGestionarUsuario1;
    private vista.InterGestionarVenta interGestionarVenta2;
    private vista.InterMotocicleta interMotocicleta1;
    private vista.InterUsuario interUsuario2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAgregarCliente;
    private javax.swing.JLabel logoPanel;
    private javax.swing.JLabel nuevoProducto;
    private javax.swing.JLabel nuevoUsuario;
    private javax.swing.JLabel obtenerRegistro;
    private javax.swing.JPanel opcionGrafico;
    private javax.swing.JPanel opcionProducto;
    private javax.swing.JPanel opcionReporte;
    private javax.swing.JPanel opcionUsuario;
    private javax.swing.JPanel opcionVenta;
    private javax.swing.JPanel opcioonCliente;
    private javax.swing.JPanel panelDesplazable;
    private javax.swing.JLabel realizarVenta;
    private javax.swing.JLabel reporteClientes;
    private javax.swing.JLabel reporteUsuarios;
    private javax.swing.JLabel reporteVentas;
    private javax.swing.JLabel suzukiPng;
    private javax.swing.JLabel verProducto;
    // End of variables declaration//GEN-END:variables

    private void restriccionUser() {

        String aux = Modelo_Usuario.restriccion;
        System.out.println("Parametro que llega a la clase FormMenu aqui");
        System.out.println(aux);
        if (aux.equals("Administrador")) {
            JOptionPane.showMessageDialog(null, "Inicio sesion como administrador");
        } else if (aux.equals("Gerente")) {
            nuevoUsuario.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Inicio sesion como gerente");
        } else {
            btnUsuarios.setEnabled(false);
            btnProducto.setEnabled(false);
            btnReportes.setEnabled(false);
            btnGraficos.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Inicio sesion como Cajero");
        }
    }

}
